In [1]:
import numpy as np 
import pandas as pd 
import os

import seaborn as sns 
import matplotlib.pyplot as plt 
import csv

from matplotlib import colors
from matplotlib.ticker import PercentFormatter

In [2]:
master = pd.read_csv('C:\\Users\\siddh\\Desktop\\DES\\Datasets For Use\\master_combined.csv')
master.head()

C:\Users\siddh\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (9,10,13,14,20,21,22,23,24,25,26,27) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,DataStore,Dataset,Provider,Location_ID,Layer_ID,SampleID,SampleDate,Longitude,Latitude,UpperDepth,...,QualSpatialAccuracy,ExtractTime,LAB_METH_CODE,LAB_METH_NAME,LAB_METH_SHORT_NAME,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,UNITS
0,SALI,QLDGovernment,QLDGovernment,QLD_3MC_153_1,2.0,2.0,01-01-1993,151.160172,-24.85381,0,...,3.0,2021-10-01T04:39:52,10A1,Total sulfur - X-ray fluorescence,Total S XRF,SALI,11-Mar-03,SALI,11-Mar-03,%
1,SALI,QLDGovernment,QLDGovernment,QLD_3MC_153_1,4.0,4.0,01-01-1993,151.160172,-24.85381,0.15,...,3.0,2021-10-01T04:39:52,10A1,Total sulfur - X-ray fluorescence,Total S XRF,SALI,11-Mar-03,SALI,11-Mar-03,%
2,SALI,QLDGovernment,QLDGovernment,QLD_3MC_153_1,5.0,5.0,01-01-1993,151.160172,-24.85381,0.2,...,3.0,2021-10-01T04:39:52,10A1,Total sulfur - X-ray fluorescence,Total S XRF,SALI,11-Mar-03,SALI,11-Mar-03,%
3,SALI,QLDGovernment,QLDGovernment,QLD_3MC_153_1,8.0,8.0,01-01-1993,151.160172,-24.85381,0.5,...,3.0,2021-10-01T04:39:52,10A1,Total sulfur - X-ray fluorescence,Total S XRF,SALI,11-Mar-03,SALI,11-Mar-03,%
4,SALI,QLDGovernment,QLDGovernment,QLD_3MC_153_1,11.0,11.0,01-01-1993,151.160172,-24.85381,0.8,...,3.0,2021-10-01T04:39:52,10A1,Total sulfur - X-ray fluorescence,Total S XRF,SALI,11-Mar-03,SALI,11-Mar-03,%

In [3]:
master['UpperDepth'] = pd.to_numeric(master.UpperDepth, errors = 'coerce')
master['LowerDepth'] = pd.to_numeric(master.LowerDepth, errors = 'coerce')

In [4]:
temp_df = master.drop(master[master['Latitude'].isnull()].index, inplace = False)

In [14]:
### Work on the temp_df dataframe. 

master_df = temp_df
temp_df

,DataStore,Dataset,Provider,Location_ID,Layer_ID,SampleID,SampleDate,Longitude,Latitude,UpperDepth,...,QualSpatialAccuracy,ExtractTime,LAB_METH_CODE,LAB_METH_NAME,LAB_METH_SHORT_NAME,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,UNITS
0,SALI,QLDGovernment,QLDGovernment,QLD_3MC_153_1,2.0,2.0,01-01-1993,151.160172,-24.85381,0.00,...,3.0,2021-10-01T04:39:52,10A1,Total sulfur - X-ray fluorescence,Total S XRF,SALI,11-Mar-03,SALI,11-Mar-03,%
1,SALI,QLDGovernment,QLDGovernment,QLD_3MC_153_1,4.0,4.0,01-01-1993,151.160172,-24.85381,0.15,...,3.0,2021-10-01T04:39:52,10A1,Total sulfur - X-ray fluorescence,Total S XRF,SALI,11-Mar-03,SALI,11-Mar-03,%
2,SALI,QLDGovernment,QLDGovernment,QLD_3MC_153_1,5.0,5.0,01-01-1993,151.160172,-24.85381,0.20,...,3.0,2021-10-01T04:39:52,10A1,Total sulfur - X-ray fluorescence,Total S XRF,SALI,11-Mar-03,SALI,11-Mar-03,%
3,SALI,QLDGovernment,QLDGovernment,QLD_3MC_153_1,8.0,8.0,01-01-1993,151.160172,-24.85381,0.50,...,3.0,2021-10-01T04:39:52,10A1,Total sulfur - X-ray fluorescence,Total S XRF,SALI,11-Mar-03,SALI,11-Mar-03,%
4,SALI,QLDGovernment,QLDGovernment,QLD_3MC_153_1,11.0,11.0,01-01-1993,151.160172,-24.85381,0.80,...,3.0,2021-10-01T04:39:52,10A1,Total sulfur - X-ray fluorescence,Total S XRF,SALI,11-Mar-03,SALI,11-Mar-03,%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2039867,ASRIS,NatSoil,CSIRO,899_SSM_SSM9_1,1.0,3.0,31-01-1991,148.798660,-32.64053,0.05,...,3.0,2021-10-01T19:04:46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2039868,ASRIS,NatSoil,CSIRO,899_SSM_SSM9_1,2.0,1.0,31-01-1991,148.798660,-32.64053,0.10,...,3.0,2021-10-01T19:04:46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2039869,ASRIS,NatSoil,CSIRO,899_SSM_SSM9_1,3.0,1.0,31-01-1991,148.798660,-32.64053,0.15,...,3.0,2021-10-01T19:04:46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2039870,ASRIS,NatSoil,CSIRO,899_SSM_SSM9_1,4.0,1.0,31-01-1991,148.798660,-32.64053,0.25,...,3.0,2021-10-01T19:04:46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2039871,ASRIS,NatSoil,CSIRO,899_SSM_SSM9_1,6.0,1.0,31-01-1991,148.798660,-32.64053,0.70,...,3.0,2021-10-01T19:04:46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
method_occurrences = pd.value_counts(master['ObservedProperty'])
method_occurrences

3A1           142117
o_id           97691
5A2            89379
2A1            61748
7B1            54732
               ...
12_HCL_ZN          1
P3B_NR_005         1
12_HCL_CU          1
P4_sat             1
12_HCL_MN          1
Name: ObservedProperty, Length: 374, dtype: int64

In [16]:
temp1 = master_df.drop(master[master['Value'].isnull()].index, inplace = False)

SyntaxError: invalid syntax (<ipython-input-23-a7519cb7d092>, line 1)